services:
  gateway-api:
    image: ${DOCKER_REGISTRY-}gateway.api
    container_name: "Api-Gateway"
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    ports:
      - "5123:8080"
    depends_on:
      - sys-db
    networks:
      - proxy-backend

  product-api:
    image: ${DOCKER_REGISTRY-}product.api
    container_name: "Api-Product"
    build:
      context: .
      dockerfile: Product.Api/Dockerfile
    ports:
      - "5279:8080"
    depends_on:
      - sys-db
    networks:
      - proxy-backend

  sale-api:
    image: ${DOCKER_REGISTRY-}sale.api
    container_name: "Api-Sale"
    build:
      context: .
      dockerfile: Sale.Api/Dockerfile
    ports:
      - "5252:8080"
    depends_on:
      - sys-db
    networks:
      - proxy-backend
      
  user-api:
    image: ${DOCKER_REGISTRY-}user.api
    container_name: "Api-User"
    build:
      context: .
      dockerfile: User.Api/Dockerfile
    ports:
      - "5259:8080"
    depends_on:
      - sys-db
    networks:
      - proxy-backend
        
  sys-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "Sys-Db"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "S1S_U53R_DB"
      MSSQL_TCP_PORT: 1234
    ports:
      - "1234:1234"
    volumes:
      - ./containers/database:/var/opt/mssql/data
    networks:
      - proxy-backend
    
  identity:
    image: quay.io/keycloak/keycloak
    container_name: keycloak-identity
    command:
      - start-dev
    ports:
      - "18080:8080"
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data

networks:
  proxy-backend:
    driver: bridge
