services:
  gateway-api:
    image: ${DOCKER_REGISTRY-}gateway.api
    container_name: "Api-Gateway"
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    ports:
      - "5123:8080"
    networks:
      - proxy-backend

  product-api:
    image: ${DOCKER_REGISTRY-}product.api
    container_name: "Api-Product"
    build:
      context: .
      dockerfile: Product.Api/Dockerfile
    ports:
      - "5279:8080"
    networks:
      - proxy-backend

  sale-api:
    image: ${DOCKER_REGISTRY-}sale.api
    container_name: "Api-Sale"
    build:
      context: .
      dockerfile: Sale.Api/Dockerfile
    ports:
      - "5252:8080"
    networks:
      - proxy-backend
      
  user-api:
    image: ${DOCKER_REGISTRY-}user.api
    container_name: "Api-User"
    build:
      context: .
      dockerfile: User.Api/Dockerfile
    ports:
      - "5259:8080"
    networks:
      - proxy-backend

networks:
  proxy-backend:
    driver: bridge
